### ISSUE TITLE
Document terms used to refer to user roles/states

### ISSUE THREAD

**Issue by hannahhubbard** [betterangels/better-angels#136]
# Discussion

> Hey guys have we landed on consistent titles for different user roles? I know @meitar and I have discussed this but has anything been decided, or is there a pattern you have been using that is working for you @meitar ?
>  
> We need terms for:
>  
> -those who are hosting a buoy plug in on their websites
> -those who have created a buoy team and will be/are sending alerts
> -those who have been sent a request to join a team
> -those who have confirmed a request and are now part of a team
> 
> Anything else? Am I off? 
> 
> Thanks

# Actionable items

* [ ] [Make Venn diagram](#issuecomment-178326489): If someone wants to make a big Venn diagram showing this visually, that might be helpful.
* [x] [Add diagram to a (new) "Glossary" page](#issuecomment-178328966): We could then add such a diagram to a "[Glossary](https://github.com/meitar/better-angels/wiki/Glossary)" page on the wiki and have a canonical place to formalize this language.

**Comment by meitar** [comment]
> those who are hosting a buoy plug in on their websites

"Buoy admins (or administrators)." We have [a wiki page dedicated to this audience](https://github.com/meitar/better-angels/wiki/Buoy-Administration-Guide).

> -those who have created a buoy team and will be/are sending alerts

This is nebulous because it could refer to a number of different user roles. I generically call this set "Buoy users."

> -those who have been sent a request to join a team

I call these "invited users."

> -those who have confirmed a request and are now part of a team

I call these "team members."

Note that again, these sets often overlap. A Buoy administrator is also a Buoy user when they create their own teams and also a team member when they confirm their membership on someone else's team.

If someone wants to make a big Venn diagram showing this visually, that might be helpful. We could then add such a diagram to a "Glossary" page on the wiki and have a canonical place to formalize this language. Again, if that would be helpful.

**Comment by meitar** [comment]
Oh and I guess other terms already commonly used include:

* **Alerter**: In the context of an alert, an "alerter" is the Buoy user who initiated the alert being sent.
* **Responder**: In the context of an alert, a "responder" is a Buoy user who both received the alert and clicked the "Respond" button after having received said alert.
* **Notified user**: In the context of an alert, a "notified user" is a Buoy user who is sent a notification of some kind (email, txt, Web push, etc.) of an alert but has not yet acted upon the notification they received.
* **Team owner**: The Buoy user who a given team was created by.

There might be other terms but these are the ones that are on the top of my head, so I think these are the only common ones.

**Comment by unquietpirate** [comment]
This is an informal usage, but something I noticed today that my testers have started saying on their own, and that I thought was kind of cute: Verbing _Buoy_ as shorthand for _Sending an Alert_. e.g. "Okay, Buoy me and let's see if it works." "Nate Buoyed me in the middle of the night last night!" etc.

**Comment by meitar** [comment]
> Verbing Buoy as shorthand for Sending an Alert. e.g. "Okay, Buoy me and let's see if it works." "Nate Buoyed me in the middle of the night last night!" etc.

[Don't Be Evil](https://en.wikipedia.org/wiki/Don't_be_evil). LOL. ;)

**Comment by hannahhubbard** [comment]
lol. uh oh. ;) 

mkay [started](https://github.com/meitar/better-angels/wiki/Glossary)

**Comment by meitar** [comment]
I'm cleaning up the issue tracker so it matches the new organization structure more appropriately. We never made a Venn diagram for this but we did make a Glossary so I'm gonna call this "done" as in good-enough-for-now and if anyone wants to make diagrams later, go for it.
