### ISSUE TITLE
Implement live-streaming to responders

### ISSUE THREAD

**Issue by meitar** [betterangels/better-angels#139]
We currently let responders upload a video that other responders can download, but this requires a full upload-download round trip. Instead, allow live-streaming, too. Perhaps using something like [WebTorrent](https://webtorrent.io/)?

**Comment by hannahhubbard** [comment]
I love this. And could we allow for the option to capture streamed videos via something like [Playback](https://mafintosh.github.io/playback/)?

**Comment by hannahhubbard** [comment]
Found Playback in [WebTorrent FAQ](https://webtorrent.io/faq) under "Can WebTorrent clients connect to normal BitTorrent clients?"

**Comment by meitar** [comment]
This issue has been migrated to betterangels/buoy#58.
