### ISSUE TITLE
Create general chatter room on Gitter to avoid overloading Buoy contributor's chat room

### ISSUE THREAD

**Issue by meitar** [betterangels/better-angels#179]
I'm not convinced we need this yet but I think we're getting close to the point where we need a "general chatter" room for "socializing/hanging out on Gitter" as distinct from "discussing Buoy work on Gitter."

Right now, we use https://gitter.im/betterangels/buoy as the only public chat room. We can also split off a more general chat room, perhaps at https://gitter.im/betterangels/better-angels for more social chatter.

When you think this becomes a priority please +1 this issue ([using the GitHub Reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)) and when we have a critical mass we'll try making that switch to this new social norm.

**Comment by hurtstotouchfire** [comment]
I guess I'm the only dissident? I think it might be hard to separate "general" from buoy chat right now.

**Comment by hurtstotouchfire** [comment]
but maybe we could move that all to better-angels and not worry too much about having occasional buoy chat in there?

**Comment by meitar** [comment]
> I guess I'm the only dissident? I think it might be hard to separate "general" from buoy chat right now.

You're not, I dissent as well. I opened this issue so we have a place to track increasing interest in this over time, not because I'm voting for a move yet.

**Comment by tambait** [comment]
I can't tell it's a priority. But in a way if I would do just translations (which is perfectly fine) all is ok now too. However if at some point I would do some programming then guess there would be different things to ask, not only related to some imagined project. :)

But, maybe I'll be more onto Buoy topic after this "getting familiar" with everything period.

**Comment by hurtstotouchfire** [comment]
I actually want this now, but can't figure out how to create it myself. Will chat in the buoy room.

**Comment by meitar** [comment]
Created https://gitter.im/betterangels/better-angels as a "general chatter" room.
