### ISSUE TITLE
Could Buoy immediately activate separate hidden mini-video/audio recording devices?

### ISSUE THREAD

**Issue by hannahhubbard** [betterangels/better-angels#63]
When a Buoy alert is activated, could it automatically and wirelessly activate mini cameras that a "victim" has hidden in their home, in a vehicle, on their body, or in any other location where they feel they could be threatened?

**Comment by meitar** [comment]
That's a super clever idea and I love the notion of integrating with IOT devices for personal protection and community response. :)

**Comment by meitar** [comment]
This issue has been migrated to betterangels/buoy#19.
